/**
 * 開発用の seed スクリプト。
 *
 * 実行: `npx tsx scripts/seed.ts`
 *
 * Pass 1 の各機能を実データで動作確認するため、Firestore と Storage に
 * 開発用のサンプルデータを冪等に投入する。
 *
 * 投入内容（spec.md §5 / spec-details.md §3 準拠）:
 * - users: 5件（作家3 + 購入者2）。`stripeOnboarded: true` を作家に設定
 * - scripts: 8件（ジャンル/キャスト/価格を分散、無料1件、全文無料1件）
 *   - 各 scripts の versions/1 サブドキュメント
 *   - サンプル PDF（pdf-lib で生成）を Storage の `scripts/{id}/v1/script.pdf` にアップロード
 * - chats: 3件（messages サブコレクションに数件のメッセージ）
 * - consultations: 3件（status を未対応/対応中/完了に分散）
 * - invoices: 2件（pending と paid）
 * - purchases: 2件（無料 + 有料）
 * - users/{uid}/favorites, history: 数件
 * - userIds: 各 user の userId に対応する補助索引
 * - config/platform: feeRate 等 + scriptTagDefinitions（26タグ）+ topPageSections
 *
 * 冪等性: 何度実行しても同じ状態になる。固定 ID で set/upsert する。
 *
 * 安全装置: NEXT_PUBLIC_FIREBASE_PROJECT_ID が "script-marcketplace" でなければ throw。
 */

import { config as loadDotenv } from "dotenv";
import { cert, getApps, initializeApp } from "firebase-admin/app";
import { FieldValue, getFirestore, type Firestore } from "firebase-admin/firestore";
import { getStorage } from "firebase-admin/storage";
import { PDFDocument, StandardFonts } from "pdf-lib";

import {
  GENRES,
  INITIAL_TOP_PAGE_SECTIONS,
  PERFORMANCE_TYPES,
  SCRIPT_TAG_DEFINITIONS,
  TARGET_AUDIENCES,
  DEFAULT_HEARING_SHEET_TEMPLATE,
} from "../src/lib/script-tags";
import { DEFAULT_NOTIFICATION_SETTINGS } from "../src/types/user";
import { INITIAL_SCRIPT_STATS } from "../src/types/script";

loadDotenv({ path: ".env.local" });

// ----------------------------------------------------------------------------
// Safety: 開発プロジェクト以外で実行禁止
// ----------------------------------------------------------------------------
// 重要: "marcketplace" は typo に見えるが Firebase プロジェクト ID の **実際の値**。
// プロジェクト作成時の誤字をそのまま採用しているため変更不可（docs/progress.md 参照）。
// 本番プロジェクトを別 ID で作成した時はそちらは安全装置でブロックされる。
const ALLOWED_PROJECT_ID = "script-marcketplace";
const PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
if (PROJECT_ID !== ALLOWED_PROJECT_ID) {
  console.error(
    `[seed] このスクリプトは ${ALLOWED_PROJECT_ID} プロジェクトでしか実行できません。現在: ${PROJECT_ID ?? "(undefined)"}`,
  );
  process.exit(1);
}

// ----------------------------------------------------------------------------
// Admin SDK 初期化
// ----------------------------------------------------------------------------
function initAdmin() {
  const projectId = process.env.FIREBASE_ADMIN_PROJECT_ID;
  const clientEmail = process.env.FIREBASE_ADMIN_CLIENT_EMAIL;
  const privateKey = process.env.FIREBASE_ADMIN_PRIVATE_KEY?.replace(/\\n/g, "\n");
  const storageBucket = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
  if (!projectId || !clientEmail || !privateKey || !storageBucket) {
    throw new Error("FIREBASE_ADMIN_* / NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET が必要です");
  }
  if (!getApps().length) {
    initializeApp({
      credential: cert({ projectId, clientEmail, privateKey }),
      storageBucket,
    });
  }
}

initAdmin();
const db = getFirestore();
const storage = getStorage();
const bucket = storage.bucket();

// ----------------------------------------------------------------------------
// サンプル PDF 生成
// ----------------------------------------------------------------------------
async function generateSamplePdf(): Promise<Uint8Array> {
  // pdf-lib の StandardFonts は Latin1 しか対応していないため、
  // 本文は英語のプレースホルダー固定にする。
  // 実台本のアップロードフロー（P2-2 Step6）が入った時点で日本語フォント対応の本物 PDF に置き換わる。
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const totalPages = 10;
  for (let i = 1; i <= totalPages; i += 1) {
    const page = pdf.addPage([595, 842]); // A4
    const { height } = page.getSize();
    page.drawText("Script Marketplace - Sample Script", {
      x: 50,
      y: height - 80,
      size: 18,
      font,
    });
    page.drawText(`Page ${i} / ${totalPages}`, { x: 50, y: height - 110, size: 12, font });
    page.drawText(
      "This is a placeholder PDF generated by the seed script.",
      { x: 50, y: height - 150, size: 11, font },
    );
    page.drawText(
      "Replace with an actual script for production use.",
      { x: 50, y: height - 168, size: 11, font },
    );
    page.drawText(`Scene ${i} - Sample dialogue line 1:`, {
      x: 50,
      y: height - 220,
      size: 10,
      font,
    });
    page.drawText("Lorem ipsum dolor sit amet, consectetur adipiscing elit.", {
      x: 70,
      y: height - 240,
      size: 10,
      font,
    });
    page.drawText(`Scene ${i} - Sample dialogue line 2:`, {
      x: 50,
      y: height - 280,
      size: 10,
      font,
    });
    page.drawText("Sed do eiusmod tempor incididunt ut labore et dolore.", {
      x: 70,
      y: height - 300,
      size: 10,
      font,
    });
  }
  return pdf.save();
}

async function uploadPdf(scriptId: string, pdfBytes: Uint8Array): Promise<string> {
  const path = `scripts/${scriptId}/v1/script.pdf`;
  const file = bucket.file(path);
  await file.save(Buffer.from(pdfBytes), {
    contentType: "application/pdf",
    resumable: false,
  });
  return path;
}

// ----------------------------------------------------------------------------
// データ定義
// ----------------------------------------------------------------------------
type SeedUser = {
  uid: string;
  userId: string;
  email: string;
  displayName: string;
  bio?: string;
  isAuthor: boolean;
};

const SEED_USERS: SeedUser[] = [
  {
    uid: "seed-author-sato",
    userId: "sato-misaki",
    email: "sato@seed.local",
    displayName: "佐藤 美咲",
    bio: "現代劇とコメディを中心に書いています。",
    isAuthor: true,
  },
  {
    uid: "seed-author-tanaka",
    userId: "tanaka-shunsuke",
    email: "tanaka@seed.local",
    displayName: "田中 俊介",
    bio: "高校演劇向けの青春物が得意。",
    isAuthor: true,
  },
  {
    uid: "seed-author-yamamoto",
    userId: "yamamoto-sensei",
    email: "yamamoto@seed.local",
    displayName: "山本 先生",
    bio: "翻案戯曲・時代劇。教員兼業の劇作家。",
    isAuthor: true,
  },
  {
    uid: "seed-buyer-hiroko",
    userId: "hiroko",
    email: "hiroko@seed.local",
    displayName: "広子",
    bio: "市民劇団の代表。",
    isAuthor: false,
  },
  {
    uid: "seed-buyer-kenji",
    userId: "kenji",
    email: "kenji@seed.local",
    displayName: "健次",
    bio: "高校演劇部 顧問。",
    isAuthor: false,
  },
];

type SeedScript = {
  id: string;
  authorIdx: number; // SEED_USERS のインデックス
  title: string;
  slug: string;
  synopsis: string;
  genres: string[];
  cast: { min: number; max: number; male: number; female: number; unspecified: number };
  duration: number;
  performanceType: string[];
  targetAudience?: string[];
  themeTags?: string[];
  scriptTags?: string[];
  price: number;
  isFreeFullText?: boolean;
  feeSchedule?: { condition: string; amount: number; note?: string }[];
  performanceHistory?: { year: number; groupName: string; venue?: string; note?: string }[];
  authorComment?: string;
};

function makeSynopsis(seed: string): string {
  // 300〜1000文字（spec §5）。簡易的にテンプレートを繰り返す。
  const base = `${seed}は、現代を舞台に登場人物たちの繊細な心の動きを描いた物語です。それぞれの過去と向き合いながら、忘れかけていた約束を取り戻そうとする姿が、やがて思いがけない再会を呼び寄せます。\n\n語り口はあくまで穏やかでありながら、観客の胸に静かに沁み入る台詞が散りばめられており、上演を通じて観る者と演じる者の両方に余韻を残す作りになっています。場面転換は最小限に抑え、台詞と人物描写で物語を編んでいくスタイルです。\n\n上演時間や配役の柔軟性も考慮して書かれており、市民劇団から学校演劇まで幅広く取り組める一作になっています。`;
  return base.slice(0, 700);
}

const SEED_SCRIPTS: SeedScript[] = [
  {
    id: "seedRomeo",
    authorIdx: 0,
    title: "ロミオとジュリエット ― 或る夏の日の記憶",
    slug: "romeo-to-juliet-aru-natsu",
    synopsis: makeSynopsis("ロミオとジュリエット ― 或る夏の日の記憶"),
    genres: ["コメディ", "恋愛"],
    cast: { min: 5, max: 5, male: 2, female: 2, unspecified: 1 },
    duration: 90,
    performanceType: ["ストレートプレイ"],
    targetAudience: ["一般"],
    themeTags: ["夏", "再会"],
    scriptTags: ["no-props", "tearjerker", "small-theater"],
    price: 1500,
    feeSchedule: [
      { condition: "1ステージ・客席100席以下", amount: 5000 },
      { condition: "1ステージ・客席101席以上", amount: 10000, note: "目安" },
    ],
    performanceHistory: [
      { year: 2024, groupName: "市民劇団 ひだまり", venue: "中央文化センター", note: "初演" },
    ],
    authorComment: "夏の終わりの空気を大切に演じてください。",
  },
  {
    id: "seedSummer",
    authorIdx: 1,
    title: "夏の約束",
    slug: "natsu-no-yakusoku",
    synopsis: makeSynopsis("夏の約束"),
    genres: ["青春"],
    cast: { min: 4, max: 4, male: 2, female: 2, unspecified: 0 },
    duration: 60,
    performanceType: ["ストレートプレイ"],
    targetAudience: ["高校演劇向け"],
    scriptTags: ["age-high-school", "adaptation-ok", "cast-adjustable"],
    price: 1000,
    feeSchedule: [{ condition: "高校演劇連盟公式大会", amount: 3000 }],
  },
  {
    id: "seedMono",
    authorIdx: 0,
    title: "星降る夜のモノローグ",
    slug: "hoshifuru-yoru-no-monologue",
    synopsis: makeSynopsis("星降る夜のモノローグ"),
    genres: ["不条理劇"],
    cast: { min: 1, max: 1, male: 0, female: 1, unspecified: 0 },
    duration: 30,
    performanceType: ["一人芝居", "短編（30分以下）"],
    scriptTags: ["monologue", "single-scene", "small-theater"],
    price: 500,
  },
  {
    id: "seedHaiko",
    authorIdx: 1,
    title: "廃校の教室にて",
    slug: "haiko-no-kyoshitsu-nite",
    synopsis: makeSynopsis("廃校の教室にて"),
    genres: ["ミステリー", "サスペンス"],
    cast: { min: 8, max: 8, male: 4, female: 4, unspecified: 0 },
    duration: 120,
    performanceType: ["ストレートプレイ"],
    targetAudience: ["一般", "大学演劇向け"],
    scriptTags: ["age-young-adult", "adaptation-ok"],
    price: 2000,
  },
  {
    id: "seedHamlet",
    authorIdx: 2,
    title: "ハムレットの独白",
    slug: "hamlet-no-dokuhaku",
    synopsis: makeSynopsis("ハムレットの独白"),
    genres: ["悲劇", "翻案戯曲"],
    cast: { min: 6, max: 6, male: 4, female: 2, unspecified: 0 },
    duration: 100,
    performanceType: ["ストレートプレイ"],
    scriptTags: ["adaptation-ok", "age-adult"],
    price: 1800,
  },
  {
    id: "seedWarai",
    authorIdx: 0,
    title: "笑いの果実",
    slug: "warai-no-kajitsu",
    synopsis: makeSynopsis("笑いの果実"),
    genres: ["喜劇", "コメディ"],
    cast: { min: 3, max: 3, male: 2, female: 1, unspecified: 0 },
    duration: 25, // 「短編（30分以下）」と一致するように調整
    performanceType: ["ストレートプレイ", "短編（30分以下）"],
    scriptTags: ["no-props", "single-scene"],
    price: 800,
  },
  {
    id: "seedMirai",
    authorIdx: 1,
    title: "未来からの手紙",
    slug: "mirai-kara-no-tegami",
    synopsis: makeSynopsis("未来からの手紙"),
    genres: ["SF・近未来", "ファンタジー"],
    cast: { min: 4, max: 4, male: 2, female: 2, unspecified: 0 },
    duration: 60,
    performanceType: ["ストレートプレイ"],
    scriptTags: ["video-production"],
    price: 0,
    isFreeFullText: true,
  },
  {
    id: "seedSakura",
    authorIdx: 2,
    title: "桜舞う季節",
    slug: "sakura-mau-kisetsu",
    synopsis: makeSynopsis("桜舞う季節"),
    genres: ["恋愛", "現代劇"],
    cast: { min: 2, max: 2, male: 1, female: 1, unspecified: 0 },
    duration: 50,
    performanceType: ["ストレートプレイ"],
    scriptTags: ["small-theater", "tearjerker"],
    price: 1200,
  },
];

// ----------------------------------------------------------------------------
// Firestore: 投入処理
// ----------------------------------------------------------------------------

async function seedConfig(db: Firestore) {
  await db.collection("config").doc("platform").set({
    feeRate: 0.165,
    payoutFee: 250,
    autoPayoutDay: 15,
    minPayoutAmount: 1000,
    badgeDefinitions: [],
    scriptTagDefinitions: SCRIPT_TAG_DEFINITIONS,
    topPageSections: INITIAL_TOP_PAGE_SECTIONS,
    genres: GENRES,
    performanceTypes: PERFORMANCE_TYPES,
    targetAudiences: TARGET_AUDIENCES,
    updatedAt: FieldValue.serverTimestamp(),
  });
  console.log("[seed] config/platform written");
}

async function seedUsers(db: Firestore) {
  const batch = db.batch();
  for (const u of SEED_USERS) {
    const ref = db.collection("users").doc(u.uid);
    batch.set(ref, {
      uid: u.uid,
      email: u.email,
      displayName: u.displayName,
      userId: u.userId,
      bio: u.bio ?? "",
      stripeOnboarded: u.isAuthor,
      isAdmin: false,
      hearingSheet: u.isAuthor ? DEFAULT_HEARING_SHEET_TEMPLATE : [],
      notificationSettings: { ...DEFAULT_NOTIFICATION_SETTINGS },
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    });
    // userIds 補助索引
    batch.set(db.collection("userIds").doc(u.userId), {
      uid: u.uid,
      createdAt: FieldValue.serverTimestamp(),
    });
  }
  await batch.commit();
  console.log(`[seed] users written: ${SEED_USERS.length}`);
}

async function seedScripts(db: Firestore) {
  // PDF を 1 つだけ生成して全 script で共有（容量節約）
  const samplePdf = await generateSamplePdf();
  console.log(`[seed] sample PDF generated (${samplePdf.length} bytes)`);

  for (const [idx, s] of SEED_SCRIPTS.entries()) {
    const author = SEED_USERS[s.authorIdx];
    const pdfPath = await uploadPdf(s.id, samplePdf);

    // thumbnailUrl: 一部のスクリプトに公開ダミー URL を設定（後続の表示テスト用）
    // 実台本の出品フロー（P2-2 Step6）が入った時点で Storage 経由に置き換える。
    const thumbnailUrl =
      idx % 2 === 0
        ? `https://placehold.co/600x400/F5F3EE/333333?text=${encodeURIComponent(s.title)}`
        : "";

    const docData: Record<string, unknown> = {
      id: s.id,
      authorUid: author.uid,
      authorUserId: author.userId,
      authorDisplayName: author.displayName,
      title: s.title,
      slug: s.slug,
      synopsis: s.synopsis,
      genres: s.genres,
      castTotal: { min: s.cast.min, max: s.cast.max },
      castBreakdown: {
        male: s.cast.male,
        female: s.cast.female,
        unspecified: s.cast.unspecified,
      },
      duration: s.duration,
      performanceType: s.performanceType,
      targetAudience: s.targetAudience ?? [],
      themeTags: s.themeTags ?? [],
      price: s.price,
      isFreeFullText: s.isFreeFullText ?? false,
      thumbnailUrl,
      pdfUrl: pdfPath,
      currentVersion: 1,
      feeSchedule: s.feeSchedule ?? [],
      // feeScheduleMin は schedule がある時のみフィールドを書き込む。
      // null を書くと Algolia の数値ファセットで意図しない挙動になりうる。
      ...(s.feeSchedule && s.feeSchedule.length > 0
        ? { feeScheduleMin: Math.min(...s.feeSchedule.map((f) => f.amount)) }
        : {}),
      performanceHistory: s.performanceHistory ?? [],
      authorComment: s.authorComment ?? "",
      hearingSheet: [],
      scriptTags: s.scriptTags ?? [],
      badges: [],
      rankings: {},
      status: "published",
      stats: { ...INITIAL_SCRIPT_STATS },
      createdAt: FieldValue.serverTimestamp(),
      updatedAt: FieldValue.serverTimestamp(),
    };

    const scriptRef = db.collection("scripts").doc(s.id);
    await scriptRef.set(docData);

    await scriptRef.collection("versions").doc("1").set({
      version: 1,
      pdfUrl: pdfPath,
      createdAt: FieldValue.serverTimestamp(),
    });
  }
  console.log(`[seed] scripts written: ${SEED_SCRIPTS.length}`);
}

async function seedChatsAndConsultations(db: Firestore) {
  // 3つのチャット: author1↔buyer1, author2↔buyer1, author1↔buyer2
  const author1 = SEED_USERS[0];
  const author2 = SEED_USERS[1];
  const buyer1 = SEED_USERS[3];
  const buyer2 = SEED_USERS[4];

  const chats = [
    {
      id: "seed-chat-1",
      participants: [author1.uid, buyer1.uid],
      participantNames: { [author1.uid]: author1.displayName, [buyer1.uid]: buyer1.displayName },
      consultation: {
        id: "seed-consultation-1",
        scriptId: SEED_SCRIPTS[0].id,
        scriptTitle: SEED_SCRIPTS[0].title,
        requesterUid: buyer1.uid,
        authorUid: author1.uid,
        statuses: { [buyer1.uid]: "consulting", [author1.uid]: "in_progress" },
      },
      messages: [
        { senderUid: buyer1.uid, type: "text", text: "上演許可についてご相談したいです。", offset: -3600 },
        {
          senderUid: author1.uid,
          type: "text",
          text: "ありがとうございます。詳細を確認させてください。",
          offset: -1800,
        },
      ],
    },
    {
      id: "seed-chat-2",
      participants: [author2.uid, buyer1.uid],
      participantNames: { [author2.uid]: author2.displayName, [buyer1.uid]: buyer1.displayName },
      consultation: {
        id: "seed-consultation-2",
        scriptId: SEED_SCRIPTS[1].id,
        scriptTitle: SEED_SCRIPTS[1].title,
        requesterUid: buyer1.uid,
        authorUid: author2.uid,
        statuses: { [buyer1.uid]: "completed", [author2.uid]: "completed" },
      },
      messages: [
        { senderUid: buyer1.uid, type: "text", text: "本日はありがとうございました。", offset: -86400 },
        { senderUid: author2.uid, type: "text", text: "こちらこそ、頑張ってください。", offset: -82800 },
      ],
    },
    {
      id: "seed-chat-3",
      participants: [author1.uid, buyer2.uid],
      participantNames: { [author1.uid]: author1.displayName, [buyer2.uid]: buyer2.displayName },
      consultation: {
        id: "seed-consultation-3",
        scriptId: SEED_SCRIPTS[5].id,
        scriptTitle: SEED_SCRIPTS[5].title,
        requesterUid: buyer2.uid,
        authorUid: author1.uid,
        statuses: { [buyer2.uid]: "consulting", [author1.uid]: "unresponded" },
      },
      messages: [
        {
          senderUid: buyer2.uid,
          type: "text",
          text: "高校演劇大会で上演を検討しています。",
          offset: -300,
        },
      ],
    },
  ];

  for (const c of chats) {
    const lastMessage = c.messages[c.messages.length - 1];
    const lastMessageAt = new Date(Date.now() + lastMessage.offset * 1000);

    await db.collection("chats").doc(c.id).set({
      id: c.id,
      participants: c.participants,
      participantNames: c.participantNames,
      // text 以外のメッセージタイプ（hearingSheetResponse / invoice）が来る場合に備えて
      // 空文字フォールバック（Firestore の undefined エラー回避）
      lastMessage: lastMessage.text ?? "",
      lastMessageAt,
      lastMessageBy: lastMessage.senderUid,
      createdAt: new Date(Date.now() - 3 * 86400 * 1000),
    });

    // messages
    for (let i = 0; i < c.messages.length; i += 1) {
      const m = c.messages[i];
      await db
        .collection("chats")
        .doc(c.id)
        .collection("messages")
        .doc(`msg-${i + 1}`)
        .set({
          senderUid: m.senderUid,
          type: m.type,
          text: m.text,
          createdAt: new Date(Date.now() + m.offset * 1000),
        });
    }

    // consultation
    await db.collection("consultations").doc(c.consultation.id).set({
      id: c.consultation.id,
      scriptId: c.consultation.scriptId,
      scriptTitle: c.consultation.scriptTitle,
      requesterUid: c.consultation.requesterUid,
      authorUid: c.consultation.authorUid,
      chatId: c.id,
      hearingSheetData: {},
      status: c.consultation.statuses,
      createdAt: new Date(Date.now() - 3 * 86400 * 1000),
    });
  }

  // scripts.stats.consultationCount を更新
  await db
    .collection("scripts")
    .doc(SEED_SCRIPTS[0].id)
    .update({ "stats.consultationCount": 1 });
  await db
    .collection("scripts")
    .doc(SEED_SCRIPTS[1].id)
    .update({ "stats.consultationCount": 1 });
  await db
    .collection("scripts")
    .doc(SEED_SCRIPTS[5].id)
    .update({ "stats.consultationCount": 1 });

  console.log(`[seed] chats + consultations written: ${chats.length}`);
}

async function seedInvoices(db: Firestore) {
  const author1 = SEED_USERS[0];
  const author2 = SEED_USERS[1];
  const buyer1 = SEED_USERS[3];

  await db.collection("invoices").doc("seed-invoice-1").set({
    id: "seed-invoice-1",
    chatId: "seed-chat-1",
    consultationId: "seed-consultation-1",
    creatorUid: author1.uid,
    payerUid: buyer1.uid,
    amount: 8000,
    label: "上演許可料",
    memo: "1ステージ分",
    status: "pending",
    platformFee: Math.floor(8000 * 0.165),
    createdAt: new Date(Date.now() - 3600 * 1000),
  });

  await db.collection("invoices").doc("seed-invoice-2").set({
    id: "seed-invoice-2",
    chatId: "seed-chat-2",
    consultationId: "seed-consultation-2",
    creatorUid: author2.uid,
    payerUid: buyer1.uid,
    amount: 5000,
    label: "上演許可料",
    memo: "高校演劇大会用",
    status: "paid",
    stripePaymentIntentId: "seed-pi-001",
    platformFee: Math.floor(5000 * 0.165),
    createdAt: new Date(Date.now() - 86400 * 1000),
    paidAt: new Date(Date.now() - 80000 * 1000),
  });

  console.log("[seed] invoices written: 2");
}

async function seedPurchasesAndFavorites(db: Firestore) {
  const author1 = SEED_USERS[0];
  const author2 = SEED_USERS[1];
  const buyer1 = SEED_USERS[3];
  const buyer2 = SEED_USERS[4];

  // 有料台本購入
  await db.collection("purchases").doc("seed-purchase-1").set({
    id: "seed-purchase-1",
    buyerUid: buyer1.uid,
    scriptId: SEED_SCRIPTS[2].id, // 星降る夜のモノローグ ¥500
    authorUid: author1.uid,
    amount: 500,
    platformFee: Math.floor(500 * 0.165),
    stripePaymentIntentId: "seed-pi-purchase-001",
    createdAt: new Date(Date.now() - 5 * 86400 * 1000),
  });

  // 無料台本購入
  await db.collection("purchases").doc("seed-purchase-2").set({
    id: "seed-purchase-2",
    buyerUid: buyer1.uid,
    scriptId: SEED_SCRIPTS[6].id, // 未来からの手紙 (無料)
    authorUid: author2.uid,
    amount: 0,
    platformFee: 0,
    createdAt: new Date(Date.now() - 2 * 86400 * 1000),
  });

  // 該当 scripts の stats.purchaseCount 更新
  await db.collection("scripts").doc(SEED_SCRIPTS[2].id).update({ "stats.purchaseCount": 1 });
  await db.collection("scripts").doc(SEED_SCRIPTS[6].id).update({ "stats.purchaseCount": 1 });

  // favorites
  const favorites = [
    { uid: buyer1.uid, scriptId: SEED_SCRIPTS[0].id },
    { uid: buyer1.uid, scriptId: SEED_SCRIPTS[3].id },
    { uid: buyer2.uid, scriptId: SEED_SCRIPTS[5].id },
  ];
  for (const f of favorites) {
    await db
      .collection("users")
      .doc(f.uid)
      .collection("favorites")
      .doc(f.scriptId)
      .set({
        scriptId: f.scriptId,
        addedAt: new Date(Date.now() - 86400 * 1000),
      });
    await db
      .collection("scripts")
      .doc(f.scriptId)
      .update({ "stats.favoriteCount": FieldValue.increment(1) });
  }

  // history
  const history = [
    { uid: buyer1.uid, scriptId: SEED_SCRIPTS[2].id, hours: 1 },
    { uid: buyer1.uid, scriptId: SEED_SCRIPTS[0].id, hours: 4 },
    { uid: buyer2.uid, scriptId: SEED_SCRIPTS[5].id, hours: 2 },
  ];
  for (const h of history) {
    await db
      .collection("users")
      .doc(h.uid)
      .collection("history")
      .doc(h.scriptId)
      .set({
        scriptId: h.scriptId,
        viewedAt: new Date(Date.now() - h.hours * 3600 * 1000),
      });
  }

  console.log("[seed] purchases / favorites / history written");
}

// ----------------------------------------------------------------------------
// 既存 seed データの掃除（冪等化のため）
// ----------------------------------------------------------------------------
async function deleteCollection(db: Firestore, path: string, batchSize = 100) {
  const collectionRef = db.collection(path);
  const snapshot = await collectionRef.limit(batchSize).get();
  if (snapshot.empty) return;
  const batch = db.batch();
  snapshot.docs.forEach((doc) => batch.delete(doc.ref));
  await batch.commit();
  if (snapshot.size === batchSize) {
    await deleteCollection(db, path, batchSize);
  }
}

async function cleanupExistingSeed() {
  console.log("[seed] cleaning up existing seed data...");
  // チャット: messages サブコレクションを先に消す
  for (const id of ["seed-chat-1", "seed-chat-2", "seed-chat-3"]) {
    await deleteCollection(db, `chats/${id}/messages`);
    await db.collection("chats").doc(id).delete().catch(() => {});
  }
  // scripts: versions と reviews も
  for (const s of SEED_SCRIPTS) {
    await deleteCollection(db, `scripts/${s.id}/versions`);
    await deleteCollection(db, `scripts/${s.id}/reviews`);
    await db.collection("scripts").doc(s.id).delete().catch(() => {});
  }
  // users: favorites/history/savedSearches サブコレクション
  for (const u of SEED_USERS) {
    await deleteCollection(db, `users/${u.uid}/favorites`);
    await deleteCollection(db, `users/${u.uid}/history`);
    await deleteCollection(db, `users/${u.uid}/savedSearches`);
    await db.collection("users").doc(u.uid).delete().catch(() => {});
    await db.collection("userIds").doc(u.userId).delete().catch(() => {});
  }
  // 単発ドキュメント
  for (const id of ["seed-consultation-1", "seed-consultation-2", "seed-consultation-3"]) {
    await db.collection("consultations").doc(id).delete().catch(() => {});
  }
  for (const id of ["seed-invoice-1", "seed-invoice-2"]) {
    await db.collection("invoices").doc(id).delete().catch(() => {});
  }
  for (const id of ["seed-purchase-1", "seed-purchase-2"]) {
    await db.collection("purchases").doc(id).delete().catch(() => {});
  }
  console.log("[seed] cleanup done");
}

// ----------------------------------------------------------------------------
// メイン
// ----------------------------------------------------------------------------
async function main() {
  console.log(`[seed] running against project: ${PROJECT_ID}`);
  await cleanupExistingSeed();
  await seedConfig(db);
  await seedUsers(db);
  await seedScripts(db);
  await seedChatsAndConsultations(db);
  await seedInvoices(db);
  await seedPurchasesAndFavorites(db);
  console.log("[seed] all done");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("[seed] failed", err);
    process.exit(1);
  });
